
import { useEffect, useRef, useState } from "react";
import { toast } from "sonner";
import { Loader2 } from "lucide-react";

export function VersionChecker() {
  const currentVersion = __APP_VERSION__;
  // Store the initial instance ID (generated by backend on startup)
  const [initialInstanceId, setInitialInstanceId] = useState<string | null>(null);
  // Use a ref to prevent multiple toasts or reloads
  const alertingRef = useRef(false);

  useEffect(() => {
    if (!currentVersion) return;

    const checkVersion = async () => {
      try {
        // Use relative path to hit backend (via proxy in dev, via nginx in prod)
        // Add timestamp to prevent browser caching of the health check itself
        const res = await fetch(`/api/health?t=${Date.now()}`);
        if (res.ok) {
           const data = await res.json();
           
           // Initialize instance ID on first successful check
           if (!initialInstanceId && data.instanceId) {
             setInitialInstanceId(data.instanceId);
             return; // Don't check mismatch on first load
           }

           // Check for EITHER version change OR instance ID change (redeploy without version bump)
           const versionMismatch = currentVersion && data.version && data.version !== "unknown" && data.version !== currentVersion;
           const instanceMismatch = initialInstanceId && data.instanceId && data.instanceId !== initialInstanceId;

           if (versionMismatch || instanceMismatch) {
              if (alertingRef.current) return;
              alertingRef.current = true;
              
              console.log(`Update detected: version=${data.version}, instance=${data.instanceId}`);
              
              const message = versionMismatch 
                ? `Refreshing to load version ${data.version}...` 
                : "New deployment detected. Refreshing...";

              toast.info(
                <div className="flex flex-col gap-1">
                  <span className="font-bold">New update available!</span>
                  <span className="text-xs">{message}</span>
                </div>,
                { duration: 5000, icon: <Loader2 className="h-4 w-4 animate-spin" /> }
              );
              
              // Force hard reload after a short delay to let user see the toast
              setTimeout(() => {
                 window.location.reload();
              }, 2000);
           }
        }
      } catch (e) {
        // Ignore errors (offline, server restarting, etc)
      }
    };

    // Check immediately on mount
    checkVersion();
    
    // Then check every 30 seconds
    const interval = setInterval(checkVersion, 30000);

    return () => clearInterval(interval);
  }, [currentVersion]);

  return null;
}
